const locale = {
    aboutHabib: "Habib is one of the co-founders of the institute and his collaboration as manager, strategic consultant, teacher and advisor in the institute is a great asset for us. He obtained his BSc. degree in Mathematics at University of Tehran in 2019. Afterwards he started his Masters degree in Mathematics in the Montreal-Regensburg ALGANT exchange program in Canada-Germany. He is currently a doctoral student at University of Montreal specialized in Symplectic Geometry. He was awarded many prizes in math competitions in university level including Gold Medal in the Iranian National Math Competition for University Students organized by the Iran Mathematical Society.",
    habibName: "Habib Alizadeh",
    aboutMostafa: "Mostafa acts as a co-founder, IT technician and strategic consultant in the institute. Department of outdoor advertisement and signage in the city of Tehran works under his supervision and he is responsible for the designation, loading and updating our website and our online activities. He holds a BSc. degree in Software Engineering and has more than five years of experience in web design.",
    mostafaName: "Mostafa Nouri",
    aboutFilip: "Filip plays an important role as scientific consultant and his collaboration in the content production, developing and creating visual and written assets appearing on our website is a great help. He is a doctoral student at University of Montreal and a good friend of Habib.",
    filipName: "Filip Brocic",
    aboutUsTitle: "How it works",
    aboutUsContent: "Here we are, trying our best to help you with every aspect of your short and long term scientific goals while you are taking your path in science. Our institute is grateful for collaboration with great minds of Iran most of whom are currently either studying or working in the best and highly ranked universities of the world. We believe that having these minds beside us will be a vigorous boost for the next generation of students of Iran which are living in a dramatic and downhearted time. We are proud to have gathered here the future of Irans Mathematics and to make a difference in our mathematical society. The Arbist institute is the first institute in Iran that offers math classes taught in foreign languages including English, French and German too. If you or your kid have a minimum knowledge of the mentioned languages you may take our classes and ‘kill two birds with one stone’. We are not limiting ourselves to private tutoring services but we step beyond and offer you free scientific and professional consultations on Konkour, your future career and field of study in university, creating a professional resume, studying abroad and immigration.",
    coFounderTitle: "Co-Founders",
    telegram: "Telegram"
}

export default locale;